# This rule is not used by the project monitoring-secrets-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.mycompany.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: monitoring-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: secret-admin-role
rules:
- apiGroups:
  - core.mycompany.com
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - core.mycompany.com
  resources:
  - secrets/status
  verbs:
  - get
