apiVersion: core.mycompany.com/v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: monitoring-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: secret-sample
spec:
  # TODO(user): Add fields here
